### ISSUE TITLE
Not working in Safari, and assistant icon shows "paused" state for every page load

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#1059]
@jab commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114847)

### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

Application version 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

on every page

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

AdGuard is not working. I am using Safari. And the AdGuard Safari "assistant" extension shows the "paused" status on its icon for every page I load.

An apparently-related error message incorrectly complains that the root certificate expired:
<img width="1594" alt="Screen Shot 2022-04-06 at 6 30 18 PM" src="https://user-images.githubusercontent.com/64992/162083034-ae07f708-633f-4242-a7b5-23ffe944b5cb.png">

This even happens for [http://neverssl.com](http://neverssl.com) (wat?):
<img width="1594" alt="Screen Shot 2022-04-06 at 6 31 56 PM" src="https://user-images.githubusercontent.com/64992/162083292-0e328ef8-761b-401c-8d33-c8ec2e96dabd.png">

The `*.adguard.com` CA cert that is installed is not expired:
<img width="1138" alt="Screen Shot 2022-04-06 at 6 32 43 PM" src="https://user-images.githubusercontent.com/64992/162083425-592ee8f0-d95d-418f-8063-feaa791e16c9.png">

Any idea what's wrong with the AdGuard setup on this machine?

### Privacy

- [X] I agree to follow this condition

---

@Aydinv13 commented on [Thu Apr 07 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114847#issuecomment-1092002352)

First of all, what version of Mac&Safari do you have? Could you write approximate steps to reproduce? How often does it happen?

---

@jab commented on [Fri Apr 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114847#issuecomment-1093014639)

macOS Catalina Version 10.15.7 (19H1824)
Safari Version 15.4 (15613.1.17.1.11, 15613)

It happens on every page load. The reproduction steps are just to (1) load any webpage, (2) observe the "paused" status showed by the AdGuard Safari assistant extension, (3) observe that AdGuard filters aren't working (as in #113732).

---

@jab commented on [Tue Apr 12 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114847#issuecomment-1096995396)

Issue is still occurring (should be unmarked as stale). Maybe AdGuard’s support for Catalina suffered a regression?

---

@jab commented on [Tue Apr 12 2022](https://github.com/AdguardTeam/AdguardFilters/issues/114847#issuecomment-1096997938)

Note there are really two issues here: (1) make AdGuard work again on systems like this and (2) improve the error reporting when something goes wrong. 

The current error reporting is inaccurate and incomplete.

**Comment by Alex-302** [comment]
@jab Moved to correct place.

**Comment by Stillness-2** [comment]
@jab When did it start? Did AdGuard work and then stop, or did it not work from the moment of installation?

**Comment by jab** [comment]
Interesting: I tried testing with Firefox with the Firefox AdGuard assistant extension, and reproduced the same behavior:

<img width="1002" alt="Screen Shot 2022-04-13 at 10 32 23 AM" src="https://user-images.githubusercontent.com/64992/163204039-2794d1ec-f34a-4651-a12c-f4361a861230.png">

So I think this issue title should have "not working in Safari" replaced with "not working in Catalina".

**Comment by Stillness-2** [comment]
@jab, do you use any antivirus or network filter? 
If open
![image](https://user-images.githubusercontent.com/12689/163277897-037476a4-ae37-4804-a865-3c27f46c73d8.png) -> Advansed ->Filtering log... Is there a display of requests to the servers when you surfing around the sites?

**Comment by jab** [comment]
0. Want to change the title of this issue, as per my previous message?
1. No, I don't use any antivirus or network filter, only AdGuard.
2. AdGuard filtering log is showing filtered requests:
<img width="982" alt="Screen Shot 2022-04-14 at 4 10 22 PM" src="https://user-images.githubusercontent.com/64992/163469206-a1adb39c-a531-4574-8d31-150c8d7ccc99.png">
3. Can I email you my com.adguard.mac.adguard.plist (and/or any other relevant settings) so you can test with the same settings on a Catalina environment and report back whether you can reproduce this? Thank you

**Comment by Stillness-2** [comment]
@jab 

1. Install last release, which released yesterday.
2. Reset settings from AdGuard menu
3. Go through settings process
4. After that if filtering not work
5. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**
6. Reproduce the issue and remember the exact time it happened;
7.  Menu --> Advanced --> **Export Logs and System Info...**
8. Menu --> Advanced --> **Export Settings...**
9. Send those files to `apple@adguard.com` and mention this issue number in the subject.

**Comment by jab** [comment]
Just installed the latest AdGuard (2.8.0.1133 release (CL-1.9.60, DNS-1.7.22)), reset settings, re-completed the settings wizard, and I no longer get the "paused" icon or the certificate error in the popup from the AdGuard assistant in either Safari or Firefox. (I also confirmed the `stackoverflow.com##div` test that @Alex-302 suggested in https://github.com/AdguardTeam/AdguardFilters/issues/113732#issuecomment-1087531206 now works as expected.) Great! Thank you for all your help with this.

I am guessing that the only reason I had to reset settings and re-complete the setup wizard is to force AdGuard to reinstall the AdGuard Personal CA cert in my System keychain, is that right? In other words, **the problem here was that the AdGuard Personal CA cert that AdGuard had previously installed expired*, and unfortunately, **AdGuard does not currently prompt the user to install a new CA cert when it detects this**?

If so, are there still some remaining followups for AdGuard to handle this situation better?

Finally, any idea how my previous AdGuard CA cert could have expired in the first place? Looking at my current one, it expires in 2042 which is far enough in the future to not worry about this happening again, but perhaps an old version of AdGuard that I previously used only installed a CA cert that expired a year or two in the future?
<img width="1138" alt="Screen Shot 2022-04-15 at 10 45 47 AM" src="https://user-images.githubusercontent.com/64992/163584917-d84e7610-4750-44ee-89d4-e1c9e8855f9c.png">

(Note, the previous Keychain Access screenshot I shared, found in this issue's description, erroneously showed the certs in my "login" keychain; I meant to show the certs in my "System" keychain, as in this screenshot, but didn't realize I'd forgotten to change to the "System" keychain, and unfortunately now it's too late to see what the previous AdGuard CA cert's expiration was since AdGuard just installed a new cert. I guess no one else noticed this either, since that seems like critical info to ask me to provide here?)
