### ISSUE TITLE
Installation issue on macOS 13 Public Beta

### ISSUE THREAD

**Issue by cryptopatik22** [AdguardTeam/AdguardForMac#1116]
### Expected behavior
System password is accepted and AdGuard installation process goes on

### Actual behavior
Error message - password is incorrect

### Customer's environment name
<img width="765" alt="Screenshot 2022-08-13 at 23 52 20" src="https://user-images.githubusercontent.com/104494839/184596769-b1ad4f51-482e-45fb-a265-abdef5c7b013.png">

 macOS 13 Public Beta

**Comment by cryptopatik22** [comment]
At least three cases:
628731
625228
624659

**Comment by ameshkov** [comment]
Probably caused by us using `AuthorizationExecuteWithPrivileges`

**Comment by harry-b** [comment]
I have managed to reproduce this problem on VM. It looks like this is the macos Venture beta issue. I tried different approaches to get sudo (applescript, AuthorizationExecuteWithPrivileges) and all of them failed.

**Comment by harry-b** [comment]
Finally turned out it is not allowed for /usr/sbin/install to read pkg file from temporary dir (on mac os Version 13.0 Beta (22A5321d) ). This is a reason of the issue. As a workaround it is possible to give full disk access rights to AdGuard VPN (from web installer) 
<img width="805" alt="Screenshot 2022-08-16 at 17 46 35" src="https://user-images.githubusercontent.com/1119809/185324767-182efbe8-113b-4028-97a6-fc987fd1a5c4.png">
