### ISSUE TITLE
Custom userscripts fail to work after update to v2.10

### ISSUE THREAD

**Issue by IVenoci** [AdguardTeam/AdguardForMac#1229]
· AdGuard for Mac Version: 2.10.0.1272 release, CoreLibs 1.11.79, DNSLibs 2.1.27
· macOS Version: Ventura 13.3.1 (22E261)
· Time of noticing problem: after update to the 2.10.0.1272 release, and reinstallation of extensions (userscripts, since they are always removed upon update)
· Reproducing the Problem: just install AdGuard and all extensions as usual
· Recurrence: Extensions have not worked so far
· VPN: macOS manual connection IKEv2 VPN used. But extensions do not work regardless of VPN server connection
· Other Notes: tried restarting system and reinstallation of AdGuard. Does not work. All extensions fail in Safari now(yes of course I have enabled AdGuard extension in Safari browser). The failed ones work well on Chrome. So the problem is within AdGuard.

**Comment by Aydinv13** [comment]
@IVenoci Hi there!

Could you please answer these questions:
1) Do you mean that after every update you have all extensions removed? That's too weird if I got you right.
2) Could you tell me if "AdGuard app or extension" and "AdGuard Extra" are running on the [test page](https://adguard.com/en/test.html)? AdGuard protection and AdGuard Extra should be on while testing.
3) The problem is only with Safari now, right? Have you made any changes in its settings? (e.g in Develop part)
4) Are you talking about extra extensions or default ones as well?

I wasn't able to catch such a problem on my device (macOS 13.3.1, Safari 16.4). 
Please try to reinstall AdGuard and if the problem persists collect the debug logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and **remember the exact time** it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by IVenoci** [comment]
1. Yes. I was very frustrated by that. Every update removes my extension(userscripts). Yet strangely this evening when I was uninstalling, the user scripts were there after reinstallation. I did not have to redownload those scripts though I just uninstalled and reinstalled.
2. Yes. Of the four, "AdGuard app or extension" and "AdGuard Extra" are marked green running.
3. Yes, it is only on safari. On Chrome I simply use Tampermonkey for scripts managing. I bought AdGuard Pro because some scripts that fail in Safari's Tampermonkey miraculously work in AdGuard on Safari.
4. Extra ones. But I am not sure whether default ones work. Is there a way to test them? But as I mentioned, those scripts work well on Chrome via Tempermonkey. So it is less likely due to the scripts themselves.

I did reinstall before I contacted support or submitted this issue. So I will just send you the logs.

**Comment by IVenoci** [comment]
> @IVenoci Hi there!
> 
> Could you please answer these questions:
> 
> 1. Do you mean that after every update you have all extensions removed? That's too weird if I got you right.
> 2. Could you tell me if "AdGuard app or extension" and "AdGuard Extra" are running on the [test page](https://adguard.com/en/test.html)? AdGuard protection and AdGuard Extra should be on while testing.
> 3. The problem is only with Safari now, right? Have you made any changes in its settings? (e.g in Develop part)
> 4. Are you talking about extra extensions or default ones as well?
> 
> I wasn't able to catch such a problem on my device (macOS 13.3.1, Safari 16.4). Please try to reinstall AdGuard and if the problem persists collect the debug logs. Here's what we need you to do:
> 
> 1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
> 2. Reproduce the issue and **remember the exact time** it happened;
> 3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
> 4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.


1. Yes. I was very frustrated by that. Every update removes my extension(userscripts). Yet strangely this evening when I was uninstalling, the user scripts were there after reinstallation. I did not have to redownload those scripts though I just uninstalled and reinstalled.
2. Yes. Of the four, "AdGuard app or extension" and "AdGuard Extra" are marked green running.
3. Yes, it is only on safari. On Chrome I simply use Tampermonkey for scripts managing. I bought AdGuard Pro because some scripts that fail in Safari's Tampermonkey miraculously work in AdGuard on Safari.
4. Extra ones. But I am not sure whether default ones work. Is there a way to test them? But as I mentioned, those scripts work well on Chrome via Tempermonkey. So it is less likely due to the scripts themselves.

I did reinstall before I contacted support or submitted this issue. So I will just send you the logs.

**Comment by IVenoci** [comment]
Are you fixing them one by one? How come they all suddenly fail?
Here is the exhaustive list of scripts I use.
1. [zhihu_enhance](https://greasyfork.org/zh-CN/scripts/419081-知乎增强)
2. [rapid_upload](https://greasyfork.org/zh-CN/scripts/424574-秒传链接提取)
3. [books1](https://greasyfork.org/zh-CN/scripts/438563-猴哥图书互助/feedback)
4. [books2](https://greasyfork.org/zh-CN/scripts/420751-图书互助)
5. [books3](https://greasyfork.org/zh-CN/scripts/435569-文献互助小帮手-读秀pdf一键下载-图书馆联盟-读秀-超星-中美百万显示ssid等索书号-各文献站-图书电商站与豆瓣的互访链接-一键复制元数据)
6. [csdn_focus](https://greasyfork.org/zh-CN/scripts/420352-csdn-focus)

Thank you. 
PS. The [remove web limits](https://cat7373.github.io/remove-web-limits/) userscript has not revived yet, on my safari, as for now.

**Comment by sfionov** [comment]
@IVenoci Hello! The bug affected all userscripts with unicode in main userscript name.

**Comment by Aydinv13** [comment]
@IVenoci 

> Yes. I was very frustrated by that. Every update removes my extension(userscripts).

Could you please send the debug logs, because it is not clear what is happening on your side when you update.
Here's what we need you to do:
1. Install the previous [build](https://github.com/AdguardTeam/AdguardForMac/releases/download/v2.9.2.1234/AdGuard-2.9.2.1234-release.dmg) of AdGuard for Mac;
2. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
3. Reproduce the issue and **remember the exact time** it happened;
4. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
5. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by IVenoci** [comment]
Sorry for the late reply. But I have already sent it days before(and yes, I did attach the issue number which is 1229). I will send again then, since I am reinstalling.
