### ISSUE TITLE
AdGuard for Mac is slowing down all traffic in Safari

### ISSUE THREAD

**Issue by KerryXEX** [AdguardTeam/AdguardForMac#1312]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.12

### Environment

```markdown
- OS: macOS Sonoma 14.0 RC2
- Safari version: 17.0
```

### What filters do you have enabled?

AdGuard Base filter, EasyList

### Issue Details

Steps to reproduce:
1. Reboot and login
2. Use Safari for different sites for a few minutes
3. Suddenly page loads are very much delayed, Ookla Speedtest app says "no internet connection" although Chrome/Edge loads pages normally

### Expected Behavior

No delays

### Actual Behavior

Since a few days I had a very awkward behaviour that all Safari/Webkit loading of web pages was extremely slow, meaning delays of 1-2 minutes until a web page would finally load.
I ruled out with other test environments the whole network, wifi, dns etc. and the behaviour would only apply to Safari, mac System connections (e.g. from Settings page) etc,  but not affect Edge, Chrome etc. Also Ookla Speedtest app would say it's not connected to the internet.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

There was no update of Sonoma beta in that timeframe and also no other changes to the network or network config. The behaviour would also only kick in after 1-2 minutes after a reboot, so first web pages would load normally and then be slowed down extremely.
The behaviour was also gone immediately when conneting to a VPN (regardless if to a remote VPN endpoint or to my Synology VPN in the same network).

After many more test I found that removing the AdGuard Mac app and Safari extensions immediately stopped the bad behaviour and everything is back to normal.

Not sure if this is anyhow related to Sonoma beta or what triggered this effect to start a few days ago.

**Comment by nicholascarey** [comment]
I have had similar issues with AdGuard for Mac since opening [this](https://github.com/AdguardTeam/AdguardForMac/issues/1228) issue back in April. 

Some websites would periodically just not load, especially (but not exclusively) sites which i was visiting for the first time. I tried everything, including regularly deleting history and cookies and turning off all extensions in Safari, but nothing worked. 

These problems only ever went away when i downgraded to v2.9.1.1217.

Since then every time there was a new version I have installed and tried it and found the same issues.

With the most recent release and macOS Sonoma I first *completely* uninstalled AdGaurd, including all hidden system files, and even disabling SIP and booting in Safe Mode to remove the system extension. 

Still having the same issues, if anything even worse, plus the additional issue of WiFi sometimes not working at all when waking from sleep. 

I am a lifetime license but i have given up on AdGuard.

**Comment by KerryXEX** [comment]
@Aydinv13  with the latest beta for Sonoma 14.1 the issue is not there anymore.
BUT I haave to admin that although the issue directly went away when uninstalling the Safari browser extensions, I still had problems again a few days later. Those could be fixed by removing my old "Location" profile (which existed since many years) and just creating a new one as a copy of "Automatic" and then setting the AdGuard Home DNS server again as first DNS responder. This wroks fine since then.

**Comment by Aydinv13** [comment]
@julianschelb seems that you're talking about AdGuard for Safari, not for Mac (desktop). If the problem persists, please create an issue in the corresponding repo.

@nicholascarey unfortunately, we didn't receive any logs from you since then, so we would be grateful if you could assist in solving this rare problem by collecting logs.

@KerryXEX we're glad your problem was resolved. Feel free to reopen the issue iа something goes wrong.
For now, I'm closing the issue.
