### ISSUE TITLE
AdGuard for macOS doesn't filter sites with expired certificates

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1323]
### AdGuard version

2.12.1.1398 release

### Browser version

Chrome 118.0.5993.88

### OS version

macOS 14.0 (23A344)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide Referrer from third-parties, Hide your User Agent, Remove X-client-Data header, Protect from DPI

### Support ticket ID

#800581

### Issue Details

Steps to reproduce:

1. Remove `sberbank.ru` from the list of HTTPS exclusions in AdGuard for macOS
2. Enable AdGuard Cookie Notices filter
3. Go to https://www.sberbank.ru/en/individualclients

### Expected Behavior

AdGuard for macOS filters sites with expired certificates, just like the Chorme extension.

### Actual Behavior

AdGuard for macOS does not filter sites with expired certificates.

### Screenshots

<details><summary>Screenshot 1:</summary>

Cookie banner:

![image](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/20c30277-f043-4f73-b60f-55a22e793819)

</details>

### Additional Information

https://github.com/AdguardTeam/AdguardFilters/issues/159139#issuecomment-1693377711

**Comment by AlexandrPkhm** [comment]
Hi @rakleed 

This is an intended behavior of the AdGuard application when it encounters a website with an expired or otherwise broken certificate. Since AdGuard uses HTTPS filtration to filter certificate-protected websites, it must determine the validity of a certificate before performing filtration. Unfortunately, we are unable to do this if the certificate is expired or broken, so we do not filter such sites and allow the browser to display its own “Certificate Issue” message. 

If you're determined to remove the ad on the Sberbank site, please use the AdGuard browser extension, as it utilises a different filtering mechanism and is able to remove the ad in question.

**Comment by rakleed** [comment]
@AlexandrPkhm but it is very inconvenient to have both an application and a standalone extension. Can you find a better solution?

**Comment by AlexandrPkhm** [comment]
@rakleed 

Unfortunately, this is a technical limitation related to the way the desktop application performs filtering rather than a deliberate decision on our part. The browser extension applies rules directly in the browser, while the desktop application performs filtering outside the browser and must establish a secure connection to the website itself. This is where an expired or broken certificate becomes an issue.

We will make sure to implement a solution as soon as we find one, but at this time we are unable to provide even an approximate timeframe.
