### ISSUE TITLE
Ads on YT's Homepage

### ISSUE THREAD

**Issue by ComfortableMilk4454** [AdguardTeam/AdguardForMac#1393]
### AdGuard version

2.13.0.1558 release

### Browser version

Chrome 122.0.6261.129 (Official Build) (arm64)

### OS version

macOS 14.4 (23E214)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, Adblock Warning Removal List

### Issue Details

Steps to reproduce:
1. Go to youtube.com

### Expected Behavior

no ads on homepage

### Actual Behavior

ads on homepage

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForMac/assets/43555540/25133c5d-1e93-46e2-aad6-bcb187321a08)

</details>

### Additional Information

There wasn't a selection for AdGuard Popups filter but I also have that filter enabled.

**Comment by ComfortableMilk4454** [comment]
It actually randomly stopped happening as of this morning ET. I'll let you know if it pops back up!

**Comment by AlexandrPkhm** [comment]
@ComfortableMilk4454 

It seems that this particular issue is related to the filters and not the application itself. If you're seeing similar ads on YouTube or any other site, we recommend reporting them through the [AdGuard Assistant browser extension](https://adguard.com/kb/adguard-for-mac/browser-assistant/), so that the correctly completed report of missed ads is immediately forwarded to our Filters team.
