### ISSUE TITLE
Disable Adguard, downloads get canceled

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForMac#145]
When I disable Adguard, by going to the menubar and clicking on Adguard icon and selecting: Disable.

My downloads get canceled in Firefox. Is there a way to prevent this from happening?

**Comment by ameshkov** [comment]
It's just how AG works, all connections are passed through it and when you disable it, AG should reset all active connections in order to stop the filtering completely.

The other option is do it like we do in Windows version. Stopping protection does not stop network filtering (including https filtering), it just stops ad blocking. So to stop network filtering you should exit Adguard.

**Comment by worldsdream** [comment]
Ah I see, I could also just disable the "adblocker" button, instead of the global button in top. That way, Adguard will not interrupt my downloads. This can be mark as resolved. Thanks!
