### ISSUE TITLE
AdGuard cannot load some video on Safari

### ISSUE THREAD

**Issue by HuaDeity** [AdguardTeam/AdguardForMac#1494]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.16.0 beta

### Browser version

Safari 18.1

### OS version

macOS Sequoia 15.1

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to Reproduce:
1. Enable AdGuard with Network Extension or Automatic Proxy filtering mode.
2. Navigate to the URL “https://humanvid.github.io” to verify if the video on this website is loading successfully.
3. Disable AdGuard and repeat the process in step 2.

### Actual Behavior

AdGuard will utilize the com.adguard.mac.adguard.network-extension (Network Extension) or adguard_service (Automatic Proxy) to replace the WebKit Networking service utilized by Safari. It appears that AdGuard is unable to load the video on this website.
Disabling AdGuard will utilize the stock WebKit Networking and the video load will be successful.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by AlexandrPkhm** [comment]
@HuaDeity Hello!

Unfortunately, we have encountered the same issue with videos not loading in Safari even when AdGuard was disabled. Please let us know if the issue still persists? And if it does, please send us the video recording of the issue along with application logs.

In order to troubleshoot the application logs, please do the following:

1. Click **AdGuard icon** in the menu bar *→ Gear → Advanced  → Logging → Logging level → Debug*.
2. Reproduce the problem, then remember the exact time it happened.
3. *Menu → Advanced → Logging → Export Logs and System Info.…*.
4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[mac]` keyword and `ISSUE_NUMBER` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by HuaDeity** [comment]
@AlexandrPkhm Hello!

The problem still exists, and I’ve attached the video and logs to the email.

**Comment by AlexandrPkhm** [comment]
@HuaDeity We have consulted with the developers, and it seems that we require the export of your AdGuard appliction settings to investigate the issue further. 
Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar *-> Gear -> Advanced  -> Export settings...*.
2. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[mac]` keyword and `ISSUE_NUMBER` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by HuaDeity** [comment]
Hello,

Sorry, but I’ve stopped using the AdGuard Desktop. The AdGuard for Safari works just fine for me.

The settings I had before were just the default settings with DNS protection turned off. Oh, and I’m using Surge alongside AdGuard Desktop.

HuaDeity
