### ISSUE TITLE
AdGuard for Mac conflict with Avast premium security for mac can't connect internet 

### ISSUE THREAD

**Issue by maprangsoft** [AdguardTeam/AdguardForMac#1512]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 2.15.2.1734 release

### Browser version

all browser

### OS version

macOS Monterey 12.7.6 (21H1320)

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Support ticket ID
997572

_No response_

### Issue Details

AdGuard for Mac conflict with Avast premium security for mac can't connect internet when avast for mac protection and enable protection AdGuard for Mac no problem when disable AdGuard protection.
help me.

### Actual Behavior

can connect internet when disable  AdGuard protection and enable  Avast premium security protection

### Screenshots

<details><summary>video</summary>

video for detail: [https://www.loom.com/share/ef25aed44d594da0b4c53f5fe1fe2f07](https://www.loom.com/share/ef25aed44d594da0b4c53f5fe1fe2f07
)
</details>

**Comment by AlexandrPkhm** [comment]
@maprangsoft Hello! 

In order to troubleshoot this issue, we need to get your application logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar *→ Gear → Advanced  → Logging → Logging level → Debug*.
2. Reproduce the problem, then remember the exact time it happened.
3. *Menu → Advanced → Logging → Export Logs and System Info.…*.
4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
   — include `[mac]` keyword and `ISSUE_NUMBER` in the subject of your email
   — specify the exact time when the issue occurred

**Comment by maprangsoft** [comment]
ok i send log file to email completed.

**Comment by AlexandrPkhm** [comment]
@maprangsoft We have examined the logs and unfortunately, due to the specifics of macOS, we are unable to resolve this issue on our end. Please contact Avast support so that they can resolve this issue on their end.
