### ISSUE TITLE
userstyles support AdGuard error 1, whenever I try to install one

### ISSUE THREAD

**Issue by kikker902** [AdguardTeam/AdguardForMac#1518]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Mac Version 2.16.1.1860

### Browser version

Safari 18

### OS version

macOS Ventura 13.7.2

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Annoyances

AdGuard Annoyances filter

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Issue Details

ANUserscriptParserErrorDomain error 1, whenever I try to install one. Either by the URL or by copying the CSS.

Failed to add extension
The operation couldn’t be completed. (ANUserscriptParserErrorDomain error 1.)
https://userstyles.world/style/3955/github-com

### Actual Behavior

Failed to add extension
![CleanShot 2024-12-19 at 09 36 02@2x](https://github.com/user-attachments/assets/c877a4bb-420c-483f-ad26-6cb34657b113)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by AlexandrPkhm** [comment]
@kikker902 Hello! 

Currently, AdGuard has some limitations regarding the Userstyles it can work with. 

Could you please send us the Userstyle that is causing this problem? You can attach the file to a GitHub comment or send the file to [qa@adguard.com](mailto:qa@adguard.com):
    - Include the keyword `[mac]` and `ISSUE_NUMBER` in the subject of your email.

**Comment by kikker902** [comment]
I noticed a other problem that seemed to have been related to it. Sometimes the AdGuard icon in Safari disappeared. So uninstalled and reinstalled AdGuard and all is fines now including the Userstyles. So seems some kind of error during the update process of the app. Think you can close the issue at this point.

**Comment by infilmity** [comment]
I have the same problem while installing FB Purity v.37.2.2 by this link:
https://www.fbpurity.com/fbpurity.THRTYX.user.js
I'm using the latest version of AdGuard 2.16.4.1870 release.
I'm unsure about the AdGuard script's problem; please help check. Thanks a lot.

**Comment by DotTheI** [comment]
The same issue with https://ext.vknext.net/vknext.user.js

**Comment by kamikaze67** [comment]
Here the same @infilmity

**Comment by kamikaze67** [comment]
Hello, is there a solution for this error? I am urgently waiting for a solution.

**Comment by mjcarvin** [comment]
> I have the same problem while installing FB Purity v.37.2.2 by this link: https://www.fbpurity.com/fbpurity.THRTYX.user.js I'm using the latest version of AdGuard 2.16.4.1870 release. I'm unsure about the AdGuard script's problem; please help check. Thanks a lot.

Hello, same issue as @infilmity with the same script.

Also tried saving it locally and installing from file, but the error "Failed to add extension
The operation couldn’t be completed. (ANUserscriptParserErrorDomain error 1.)" was identical.

**Comment by kamikaze67** [comment]
It is still not possible to install userscripts. I installed the new update today.

![Image](https://github.com/user-attachments/assets/41099204-5f19-4000-865e-ff657dfcb3ab)

**Comment by DotTheI** [comment]
@AlexandrPkhm, shouldn’t this be reopened, maybe?

**Comment by kamikaze67** [comment]
Please solve the problem for us. Don't leave us in the lurch.

**Comment by infilmity** [comment]
> [@kikker902](https://github.com/kikker902) Hello!
> 
> Currently, AdGuard has some limitations regarding the Userstyles it can work with.
> 
> Could you please send us the Userstyle that is causing this problem? You can attach the file to a GitHub comment or send the file to [qa@adguard.com](mailto:qa@adguard.com): - Include the keyword `[mac]` and `ISSUE_NUMBER` in the subject of your email.

I tried uninstalled and reinstall but still no help, and more users facing same issue, so please check and don't close this case, thank you.

**Comment by mjcarvin** [comment]
FB Purity can be installed manually.

1. Go to https://www.fbpurity.com/install.htm and save the latest version locally
2. Open the local version in a text editor (I used VS Code)
3. I took out the `@author` metadata property because it doesn't appear on [Adguard's published list of compatible metadata](https://adguard.com/kb/general/extensions/?clid=Y1hXNA&utm_campaign=userscripts&utm_medium=preferences&utm_source=mac#development). Yes, th
4. In your text editor, copy the entire body - top to bottom
5. In Adguard, go to Settings > Extensions
6. Click the + dropdown and select "Create userscript..." and a userscript skeleton appears.
7. Select the entire skeleton and paste in the version from your text editor
8. Save the file and close the window. 
9. In the Extensions window, make sure the Facebook Purity extension's checkbox is selected
10. Go to Facebook and hopefully you see the FBP button in the upper right corner!

Drawbacks:
- This might require manual updates every time there's a new version out
- The options menu (gear icon at far right end of extension list item in Extensions window) has "Homepage" and "Reinstall" greyed out. Adding a `@downloadURL` property with the script's URL reintroduces the meta name error.
- I still don't know why a copy/paste works but installing from a URL doesn't.

Hope this helps!
