### ISSUE TITLE
Adguard doesn't filter ads in sub-apps in WebCatalog app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#165]
https://getwebcatalog.com/ - it allows to launch other apps within WebCatalog app. 

It's added to the filtered apps list 

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21977422/c309eb0e-dbde-11e6-87b8-1d0645b2f063.png)

</details>

but ads are still being displayed, for instance, in youtube app

<details>

![ads](https://cloud.githubusercontent.com/assets/15856304/21977428/c7b54c16-dbde-11e6-94bd-2f74eb958659.png)

</details>

Reproduced on MacOS X 10.12.2, Adguard 1.4.0.

Ticket: 1389893

**Comment by Rediwed** [comment]
All application traffic within from web-apps within WebCatalog is routed thru /content/MacOS/WebCatalog_Real/, as evident by using Little Snitch to sniff the actual data.

Also, I tried manually adding the web-apps in `/Volumes/$user/Applications/WebCatalog\ Apps/` but these applications refused to show up in the filtered application list.

**Comment by ameshkov** [comment]
@Stillness-2 please take a look.

If there are no simple solution, consider adding a workaround specifically for WebCatalog app.

**Comment by Rediwed** [comment]
I don't believe this problem to be WebCatalog specific, and thus the title might be misleading. 

Any way to proof wether this issue also persists in other applications that do not route traffic thru their xxxx.app but rather thru a Unix executable subsidiary?

**Comment by ameshkov** [comment]
As I recall, most of the apps store this kind of executables inside of the `*.app` dir. Unlike WebCatalog though.

**Comment by Rediwed** [comment]
@quanglam2807 is the developer of WebCatalog, he might be able to shed some light on this!

**Comment by quanglam2807** [comment]
@ameshkov So basically, when an app installed from WebCatalog is launched, it called a bash script to start WebCatalog.

Also, the main executable file of WebCatalog is a bash script, not a binary. (WebCatalog.app is an `app bundle with generic` not an `app bundle with Mach-O thin (x86_64)`) So maybe Adguard fails to detect when WebCatalog is running.

This is what I think:

Users app `WebCatalog` to filtered list. Adguard remembers that when the executable file of WebCatalog is running, block ads). But in reality, the executable file only run in a few seconds to call the real binary file `WebCatalog_Real` which Adguard does not detect. 

I use this approach to trick the macOS because the OS does not allow to launch multi-instance of an app from Launchpad. So by doing this, macOS will think WebCatalog is not running and allow it to run again. You can take a look at the `afterPack` code  https://github.com/webcatalog/desktop/blob/master/packager.js

The solution I can suggest is to add an exception for only WebCatalog. But maybe you guys will find out something better.

**Comment by ameshkov** [comment]
@quanglam2807 thank you for clarification!
