### ISSUE TITLE
Inform the user about closed connection to a website with EV certificate

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#228]
**edited by @ameshkov**
https://github.com/AdguardTeam/AdguardForMac/issues/228#issuecomment-325919188

Original description: <details>

### Steps to reproduce
1. Visit a website with SSL for the first time in Google Chrome since installing Adguard 1.5.0 beta
2. Experience an ERR_SSL_VERSION_INTERFERENCE error page for a few seconds
3. Automatically reloads the page as per usual

### Expected behavior
Chrome loads the website normally.

### Actual behavior
Chrome displays an ERR_SSL_VERSION_INTERFERENCE error page for a few seconds before refreshing the page automatically and loading the website.

<details><summary>Screenshot:</summary>

<img width="665" alt="err" src="https://user-images.githubusercontent.com/29296810/29849262-ef521b1e-8d68-11e7-9ca1-19e5eac881fd.png">

</details>

### Customer ID 
1552859

### Your environment
* Environment name and version:
Chrome Version 61.0.3163.59 (Official Build) beta (64-bit)
macOS Version 10.13 Beta (17A358a)
Adguard for Mac Version 1.5.0 beta
Adguard Chrome Extension Version 2.6.7

* Any specific potentially conflicting software installed:
None
</details>

**Comment by ameshkov** [comment]
Do you have "Do not filter EV certificates" enabled?

**Comment by planet0** [comment]
Yes, this was whilst having that option enabled.

**Comment by ameshkov** [comment]
> Yes, this was whilst having that option enabled.

Then it's intended, unfortunately. It happens for every new website with EV certificate AG encounters for the first time.

You see, the problem is that when AG learns that certificate is EV, it should stop filtering it immediately, and the only way to do it without actually decrypting anything, is to close the connection.

**Comment by planet0** [comment]
Thanks for the explanation, @ameshkov. Would be there be any way to inform the user when the connection is closed for the first time via a notification to say that this is intentional? Or to provide an explanation underneath the option to know what to expect?

**Comment by ameshkov** [comment]
> Would be there be any way to inform the user when the connection is closed for the first time via a notification to say that this is intentional? Or to provide an explanation underneath the option to know what to expect?

It makes sense, let's transform this issue then.

**Comment by ameshkov** [comment]
First of all, let's add "Exclusions..." setting for websites with EV certificate:
https://uploads.adguard.com/up04_uwv4h_AdGuard_Preferences_-_Network.png

So that user could force filtering of a website even if EV certificate is in use.

**Alert text**
Title: `Connection to example.org has been closed`
Text: `"example.org" certificate has been added to EV exclusions. Websites with this certificate will not be filtered unless the respective option for EV certificates is disabled.`
Button: `Filter anyway`

Clicking "Filter anyway" adds website to the "Exclusions" list.

**Comment by Stillness-2** [comment]
I found some issues... reopen
