### ISSUE TITLE
Websites do not load when AdGuard is used along with Freedom

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#252]
From the Telegram chat:
> Hi, been using AdGuard for a while now for both iOS and macOS and love it. But I'm experiencing a weird problem on my mac, where if I run both Freedom app (https://freedom.to/) and AdGuard, no websites won't load. As soon as I quit one of the apps, I can access websites again. Any idea where this problem might be?

Need repro

**Comment by eivindml** [comment]
Adding some more details here. Not sure if relevant, but Freedom modifies the proxy list:

<img width="780" alt="screen shot 2017-11-09 at 07 54 54" src="https://user-images.githubusercontent.com/202450/32592432-edc150e2-c523-11e7-8d1e-0a3d98fbb17a.png">

**Comment by eivindml** [comment]
@zebrum No I made sure it's not added to the list. But I have also tried adding it to test that, but it's not working. :/ 

Should it preferably be added or not?

**Comment by zebrum** [comment]
when the app added to the list, it is working on my side. so, recheck it, please.
maybe some different settings though.

**Comment by eivindml** [comment]
I now have it added to the list, also restarted my computer without any difference. 

It happens if either "Ad Blocker" or "Privacy Protection" is enabled.

<img width="373" alt="screen shot 2017-11-10 at 10 07 55" src="https://user-images.githubusercontent.com/202450/32650784-582875ba-c5ff-11e7-9694-d53ee7fb9b0a.png">

This is the rest of my settings:

<img width="562" alt="screen shot 2017-11-10 at 10 08 07" src="https://user-images.githubusercontent.com/202450/32650832-805567aa-c5ff-11e7-8d21-28dd96e62292.png">
<img width="562" alt="screen shot 2017-11-10 at 10 08 10" src="https://user-images.githubusercontent.com/202450/32650833-806eb732-c5ff-11e7-8598-46bc2dc8aa10.png">
<img width="611" alt="screen shot 2017-11-10 at 10 08 13" src="https://user-images.githubusercontent.com/202450/32650834-809bc286-c5ff-11e7-88d2-6ecd7a7ad85c.png">

**Comment by eivindml** [comment]
It's only when "Filter https protocol" is enabled. The websites stops loading because this resource won't load:
![screen shot 2017-11-10 at 10 23 04](https://user-images.githubusercontent.com/202450/32651564-b35977de-c601-11e7-8c69-0a79c0b61979.png)

**Comment by zebrum** [comment]
@eivindml  both apps works as expected. what if you try to uncheck those proxy settings from your first screenshot?

**Comment by eivindml** [comment]
@zebrum Those proxy settings are automatically enabled and disabled by Freedom app when it starts it's session.

... 

OK, I actually found the solution right now after having problems with this for many months! 

When I run both apps at the same time, I saw in web inspector's timelines that resources related to AdGuard never would load from adguard.com site. So I thought maybe Freedom app is doing something, and if I could whitelist adguard.com in Freedom, then things would work. I followed the [instructions here](http://support.freedom.to/article/106-freedom-desktop-whitelisting) and added adguard.com, and now everything seems to work! 🎉

But I'm not sure why it never worked with both apps on my system, but it did on other's? Maybe someone can check if adguard.com is added to the the proxy whitelist on their system?

**Comment by ameshkov** [comment]
Guys, I'll increase the priority of this issue.

It might be that we have it with any local proxy, and it is quite serious then.

**Comment by vozersky** [comment]
[logs.zip](https://github.com/AdguardTeam/AdguardForMac/files/1690236/logs.zip)

reproduced, take a look @Stillness-2 @zebrum
the pages were actually loaded, but it takes like 2 minutes

**Comment by zzebrum** [comment]
@eivindml 
reopen if the problem still persists.
