### ISSUE TITLE
Adguard downgrades TLS version in case of connection error

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#300]
### Steps to reproduce
1. Disallow use of TLS 1.1 and lower in network settings
2. Launch AdGuard
3. On Firefox, loading a page will display an Unsupported protocol error
4. Other browsers work fine

### Expected behavior
AdGuard should respect the user's network settings and only use TLS 1.2+

### Actual behavior
On Firefox, AdGuard falls back to TLS 1.1

<details><summary>Screen Capture:</summary>

Available under 1672992

</details>

### Customer ID 
1672992

### Your environment
* Environment name and version: (e.g. Chrome 59): AdGuard 1.5.3, Firefox_latest, Opera_latest

**Comment by majkassab** [comment]
:)

**Comment by ameshkov** [comment]
> Disallow use of TLS 1.1 and lower in network settings

@majkassab could you please elaborate where exactly have you changed this?

Did you use `about:config` in Firefox or is it something else?
It's just by default, AG uses the highest TLS version specified by the browser.

**Comment by majkassab** [comment]
@ameshkov 
-yes i use about:config in firefox to block TLS 1.1 & 1
-This is the configuration i use to make firefox more secure:
security.ssl3.rsa_des_ede3_sha		False
security.tls.version.min				3
security.tls.version.max				4
media.peerconnection.enabled			False
security.ssl3.rsa_aes_128_sha;			false
security.ssl3.rsa_aes_256_sha;			false
security.mixed_content.block_display_content;true
security.OCSP.require;true
security.ssl.require_safe_negotiation true
security.ssl.treat_unsafe_negotiation_as_broken;true
browser.formfill.enable;false
privacy.resistFingerprinting;true
camera.control.face_detection.enabled;false
browser.cache.disk.enable;false
browser.cache.disk_cache_ssl;false
browser.cache.offline.enable;false
geo.enabled;false
media.webspeech.synth.enabled;false

-my problem is sometime adguard switch connection from TLS 1.2 to 1.1 and to solve the problem i turn off and turn on again adguard(mac version) to continue on TLS 1.2 and sometime i refresh/reload page(rarely)

-google.com and google.com.lb are the most affected by this problem (maybe because i use it a lot)

**Comment by vozersky** [comment]
@majkassab hello! please try this build, it fixes the TLS problem: https://uploads.adguard.com/up05_fopwa.dmg
