### ISSUE TITLE
Kernel panic during installing the 1.5.6 update

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#305]
https://uploads.adguard.com/etywa.panic

### Customer ID 
1824380

### Your environment

* Application version: 1.5.3 > 1.5.6
* macOS: 1013
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by planet0** [comment]
Experienced an unusual kernel panic shortly after installing 1.5.6 back on my Mac. Fully removed AdGuard (inc. leftover files) more than a week ago, and macOS installed the Security Update [2018-001](https://support.apple.com/en-us/HT201222) since then. Also using Thunderbolt Ethernet now instead of Wi-Fi.

Don't usually get them (last panic was a few years ago), so it is very coincidental timing for a panic to occur shortly after the install, straight when I quit the Google Chrome app after the AdGuard install.

I made a copy of the .panic file found in the "/Library/Logs/DiagnosticReports" but not sure if anything else is needed and if it's safe or private to upload here.

**Comment by Stillness-2** [comment]
@planet0 you can upload here .panic file. It is enough and safe. :)

**Comment by planet0** [comment]
Thanks @Stillness-2 :)
[Kernel_2018-04-28-172720.panic.zip](https://github.com/AdguardTeam/AdguardForMac/files/1957482/Kernel_2018-04-28-172720.panic.zip)

**Comment by Stillness-2** [comment]
For current version it is not relevant.
