### ISSUE TITLE
Safari delays before page starts loading

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForMac#326]
1. it always happens if first time visiting a URL
2. the subsequent visits on the same URL/sub-URL will be normal
3. come back to the visited URL some time later, it delays again.

Looks like after AG validates everything on a domain (which takes time), it then gives a fast track pass to the subsequent visits until the pass expires, something like that.

If I turn off AG and use those browser-extension AD blocker like ABP, uBlock Origin, with the exact same filters subscribed, I don't have this issue at all, pages always start loading immediately.

Standard alone version of AdGuard 1.5.8

Last Mojave beta, but same happens also with High Sierra
Safri Version 12.0 (14606.1.36.1.9)

**Comment by karina-archazh** [comment]
Hi, 

I cant repeat this issue on Safari 12. Could you pleasу send me your adguard settings and filters list?

**Comment by michael1900** [comment]
Hi, all stock filters and stock setting. Tried also different combinations but more or less nothing is changed.

**Comment by sh2sg** [comment]
@michael1900 thanks for moving my post to here :-) looks like you encountered similar problem.

@karina-archaz I originally posted on AdGuard forum (https://forum.adguard.com/index.php?threads/safari-delays-before-page-starts-loading.29305/), but that place looks like a ghost town... hope GitHub is a better place to discuss and troubleshot...

I tried to purchase multiple licenses for all the Mac at home as Mojave is coming and AdGuard seems to be the only Ad Blocker that allows to subscribe filters under Mojave/Safari12, but I am really irresolute after try-out, due to this performance issue.

The delay is obvious, visiting any URL, by clicking the link, or opening from bookmark, or entering from address bar, if this domain has not been visited for some time, there is a noticeable delay (or stuck) before Safari shows page loading progress, this happens even on local web site, I am with 1Gbps ISP, I don't have any Internet latency issue when AG is turned off.

Not only page loading delay, but some other actions are also delayed, one sample is http://www.speedtest.net/, after clicked "Go" button, it takes 10 seconds to start speed testing when AG is on, you can compare it with AG off, or using other AD Blocker.

I am not sure if AG needs to call home to validate something, it doesn't look like normal if it is a purely local app, but this intermittent delay really drives me nuts.

**Comment by sh2sg** [comment]
Below 2 network activity recording on the same URL (https://github.com/AdguardTeam/AdguardForMac/issues)

AdGuard spent more time on establishing connection and SSL handshake, 

AdGuard
![adguard](https://user-images.githubusercontent.com/3245152/45010378-d2bf9800-b03f-11e8-8e3c-62550fd6c53e.jpg)

uBlock Origin
![ubo](https://user-images.githubusercontent.com/3245152/45010382-d81ce280-b03f-11e8-839b-9674bd3723d0.jpg)

**Comment by michael1900** [comment]
I think there will not be a solution. Same problem is also on windows. I think it's by design.

**Comment by sh2sg** [comment]
I guess the performance problem is due to SSL, it takes too long time to complete the handshake comparing with Browsers, in fact it causes request broken when visiting internal https corp sites (error message below, in Win10 IE11), I have to exclude internal sites...

![snipaste_2018-09-05_11-22-51](https://user-images.githubusercontent.com/3245152/45069362-b0408400-b0fe-11e8-9bf5-4342427d160e.jpg)

**Comment by michael1900** [comment]
Why no one dev reply to this?

**Comment by michael1900** [comment]
I think never will be solved this problem. Bah...

**Comment by ameshkov** [comment]
@michael1900 sorry for the delay.

Guys, the thing is that we're in process of migrating to a brand new filtering engine (https://adguard.com/en/blog/introducing-corelibs/), and all the networking issues are postponed till the first beta of the new Mac version is out.

**Comment by ameshkov** [comment]
I'd say 99% of the performance issues are finally resolved in today's AdGuard for Mac [nightly version](https://adguard.com/en/blog/adguard-for-mac-gets-nightly/) -- [direct link](https://agrd.io/mac_nightly).

Most of them were about the overhead added by https filtering when the HTTPS connection is established. We cannot get rid of it completely for obvious reasons - there are two encrypted connections instead of one, but we had to make it as low as possible.

On my MBP with the previous nightly (and stable version as well), the overhead was about 100-120ms, and on the new one, it is about 20-30ms. Once the connection is established, the overhead is close to zero. And thanks to HTTP/2 support, these connections are kept alive and reused for a long period of time (unlike HTTP/1, browsers generally do not let them live for too long).
