### ISSUE TITLE
linkedin.com not blocked on nightly

### ISSUE THREAD

**Issue by JonoHaysom** [AdguardTeam/AdguardForMac#401]
### Steps to reproduce

1. head to LinkedIn.com
2. top ad shown and the Adguard assistant doesn't load so I'm unable to block it manually
3.
4.

### Expected behavior
no ads and the adguard assistant should show

### Actual behavior
some ads show and no adguard assistant loads

<details><summary>Screenshot:</summary>

![screenie](https://user-images.githubusercontent.com/8393299/50920833-da64d280-145f-11e9-8afc-5954f27512b2.jpg)

</details>

Running the last MacOs Mojave developer beta and the latest version of safari

**Comment by zzebrum** [comment]
@JonoHaysom hi! About missed ad, it's better to report here: https://reports.adguard.com/en/new_issue.html

Assistant is not showing on the site - looks like a bug to me, because it is present with v2.5.14

You've mentioned in other thread that you [found a conflict](https://github.com/AdguardTeam/AdguardAssistant/issues/263#issuecomment-448111281) - what was that?

**Comment by JonoHaysom** [comment]
@zzebrum the conflict was a rule, but that seems to have not worked.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #675](https://github.com/AdguardTeam/CoreLibs/issues/675) via [**ZenHub**](https://www.zenhub.com/)
