### ISSUE TITLE
Improve the app accessibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#406]
Visually impaired users cannot even open AdGuard menu.

Also, we should test AdGuard with a screen reader / voiceover.

**Comment by veronikasav** [comment]
@ameshkov A new request from one of our users. A screen reader called VoiceOver in the MacOSX operating system.  2 times quickly by pressing Ctrl + Option + M, the user can open the menu. There is no problem in this part.
To click a button or link with VoiceOver, you need to press Ctrl +  Option + Space.
He finds Adguard in the menu and he can't see the contents of the program when he presses these keys. Nothing opens up. In order to open this section, he needs help from someone. One has to click through the mouse.

Could you please take this into account?

**Comment by Stillness-2** [comment]
@veronikasav what version do users use?

**Comment by demirolcen** [comment]
Good day, if it's a translation mistake, I'm sorry for that.
I am using google translater.
I wrote to your support teams about this problem.
I'm using the Mojave version.

**Comment by Stillness-2** [comment]
@demirolcen try new AdGuard beta 

https://agrd.io/mac_beta
