### ISSUE TITLE
Search filters small issues

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForMac#422]
1.a
<details>

![image 2](https://user-images.githubusercontent.com/44832195/53168057-d4c7e400-35ea-11e9-8a98-dccf15fd0bab.png)

</details>

1.b
<details>

![image 3](https://user-images.githubusercontent.com/44832195/53168097-edd09500-35ea-11e9-9be4-72de01cce662.png)

</details>

2.

https://uploads.adguard.com/slbdzd8lrije1.mp4

3. I'm not sure how I did it, though :)

https://uploads.adguard.com/AdGuard_Preferences_-_Filters_2019-02-06_18-37-08.png

**Comment by slavaleleka** [comment]
the third one caused by search (type something and delete it)

<h4>
<details>
  <summary>also reproduced here:</summary>
<br/>

![2019-02-27 22 50 17](https://user-images.githubusercontent.com/45171506/53518724-b37f6000-3ae2-11e9-8e2d-ed1c19c97f47.png)

![2019-02-27 22 52 37](https://user-images.githubusercontent.com/45171506/53518738-ba0dd780-3ae2-11e9-8910-55107ad94fdc.png)


</details>
</h4>
