### ISSUE TITLE
Block/untrust Qaznet root CA?

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardForMac#566]
Not sure where or how to report this:

The government of Kazakhstan has forced domestic ISPs to force their internet users to install a new Qaznet root CA that functions as a MITM for "security" purposes:

https://www.intellinews.com/bnetech-kazakhstan-attempts-to-spy-on-citizens-web-use-via-encryption-busting-qaznet-trust-certificate-164852/

Example – Facebook domains signed by malicious Qaznet CA: https://gist.github.com/darkk/8356d84eabeb472120a92b7e10626cf4

Since in the desktop/premium versions of AdGuard, the user's internet traffic is encrypted via AdGuard's local certificate as a local trusted MITM, I assume that AdGuard should deem TLS connections to Qaznet-signed domains as not trustworthy. (If it hasn't been done already, and if necessary.)

(Obviously this would be a cross-platform request, not just for the macOS version.)

**Comment by TheHasagi** [comment]
@JayBrown 

This certificate is not "must-have" or optional to be installed on the device.

**Comment by ameshkov** [comment]
Let me please chime in and explain this in detail because the matter is quite sensitive.

First of all, AdGuard does not "block" the domain if it cannot verify the certificate. It simply does not try to filter HTTPS anymore, and after that, it's up to the client app (browser) to decide what to do with it.

Our goal is to repeat the very same behavior the browser has. So if any browser decides to distrust Qaznet CA, we will do this as well for this browser.

Personally, I find the idea of the government-level MITM disgusting, highly insecure, and dangerous for the future of the Web.

**Comment by ameshkov** [comment]
See the update:
https://github.com/AdguardTeam/CoreLibs/issues/1089
