### ISSUE TITLE
Disconnecting from Ethernet while your Mac is in sleep mode results in AdGuard being unable to filter local content

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#599]
### Steps to reproduce
1) use a wired Ethernet network connection
2) activate the sleep mode of your Macintosh
3) remove the Ethernet cable from your Macintosh
4) wake your Macintosh up from sleep
5) after five seconds connect the Ethernet cable again to the computer
6) open local pages
7) the error with AdGuard for Mac should appear

### Expected behavior
AdGuard should filter local content without depending on internet connection

### Actual behavior
Filtering breaks

<details><summary>Screenshot:</summary>
<img width="640" alt="Certificate" src="https://user-images.githubusercontent.com/33634917/65671407-d90c2200-e04f-11e9-8c2c-a2111e92ce07.png">
</details>

### Customer ID 
2250582

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS Mojave, Google Chrome
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) none detected

**Comment by Stillness-2** [comment]
@akmLaVx At this point AdGuard doesn't filter any local network traffic by default. I don't understand how it filtered before disconnect ethernet. :)

**Comment by nexttoyou** [comment]
> @akmLaVx At this point AdGuard doesn't filter any local network traffic by default. I don't understand how it filtered before disconnecting the ethernet. :)

That’s a quite theoretical question. As it just happens as described, the answer most probably would be that while AdGuard might not filter local connections specifically it is still acting on a networking level, otherwise it could not work system wide at all.

Besides this, are you using link aggregation or an ethernet interface via Thunderbolt? If not, you most probably will never have the problem described.

**Comment by ameshkov** [comment]
@Stillness-2 "local" is not about "localhost", this is just a local network connection

**Comment by ameshkov** [comment]
The issue will go away with release 2.5 anyway as we're going to start using NetworkExtensions instead of kernel extensions

**Comment by nexttoyou** [comment]
Sigh … Well, it even happens here with using a standard Ethernet connection (instead of slower link aggregations via Thunderbolt etc.) after sleep/wake up. As we have a dual stack connection (fixed IPv4 and IPv6 addresses) I already deactivated IPv6 entirely because I found out that after changing from IPv4 to IPv6 (seems to happen automatically from time to time) this also renders AdGuard non-functional. So switching it off and on again (™ "The IT Crowd") looks like my destiny for some more time. Quite surprisingly this never ever happened with Little Snitch.
