### ISSUE TITLE
Dock icon keeps re-appearing

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#762]
### Steps to reproduce
1. Update to 2.5.0.902 release
2. Upon each system restart, AdGuard would place an icon on macOS's Dock

### Expected behavior
Dock icon shouldn't appear unless one of AdGuard's windows are open

### Actual behavior
Dock icon constantly appears even if AdGuard is just working in the background

<details><summary>Screenshot:</summary>

![image001](https://user-images.githubusercontent.com/33634917/97089168-bbd4c900-163e-11eb-81e3-26f1828419a5.jpg)

</details>

### Customer ID & logs
2970570

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS 10.14.6, AdGuard 2.5.0.902 release (CL-1.7.119)
* Any specific potentially conflicting software installed: None reported

**Comment by Eugene-Savenko** [comment]
It's the Recent apps section, it contains recently launched apps.

<details>

![image](https://user-images.githubusercontent.com/15856304/97106471-7cec5500-16ca-11eb-91cd-0cd94b02a02e.png)

</details>

**Comment by ncp2000** [comment]
Issue isn’t related to Recent apps showing in the dock (which is of course expected behaviour). 

Issue is different: before the latest update, AdGuard would launch in the background (with a menu icon in menu tray, top right of the screen) but NOT appear in the dock. 

All the previous visions of AdGuard launched in the background with no Dock icon.

**Comment by zzebrum** [comment]
@ncp2000 please, provide a screenshot

**Comment by Eugene-Savenko** [comment]
It was always like that on my end—AdGuard starts upon the system boot and appears in the recent apps in the dock (@zebrum the screenshot is attached above).
