### ISSUE TITLE
AdGuard will block Surge DNS over HTTPS requests

### ISSUE THREAD

**Issue by Hackl0us** [AdguardTeam/AdguardForMac#778]
AdGuard provided an official tutorial for fixing compatibility with macOS Big Sur. 
In the 2nd example, Adguard shows how to work with Surge.

https://kb.adguard.com/en/macos/solving-problems/big-sur-issues#example-2-configuring-an-upstream-surge-proxy

I followed the tutorial and configured the Surge and Adguard Advanced Settings, but it doesn't work as expected. I cannot access any webpages and any proxies configured in Surge.

I noticed that the Chrome stuck at the `Resolving Host...` when I tried to access a new website. So I guess this might be caused by DNS resolving issues.

Surge supports 2 ways to resolve domain names, one is the basic DNS based on UDP protocol, the other one is DNS over HTTPS (DoH).

The tutorial that Adguard provided only worked for the original DNS, but doesn't work for the DoH. Adguard will filter the DoH request just like other HTTPS traffic and Surge cannot obtain resolve hosts from DoH server. 

I tried to list DoH domain / URL into AdGuard whitelist, sill doesn't work.

**Comment by Chinaski1** [comment]
Hello there!

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

**Comment by ngorskikh** [comment]
@Hackl0us Hi! Allow me to also chime in. 
First of all, Surge most certainly should NOT be in your filtered applications. If you've added it there, please remove it.
Secondly, unfortunately, what you are trying to accomplish (using DNS functionality in Surge) is not possible together with AdGuard. When you use AdGuard together with Surge, all traffic goes through AdGuard first, and then through Surge. DNS resolution happens before either of them have any chance to interfere with it, so it happens as normal, through the system resolver.
DNS functionality in Surge would work if applications used the local Surge proxy directly (not through AdGuard's outbound proxy), but in that case AdGuard can't filter your traffic, because Apple has disallowed filtering of traffic between two local processes.

**Comment by Hackl0us** [comment]
@Chinaski1 I have already send the logs to that email box, thanks.

@ngorskikh Hi, thank you for your reply. I'm pretty sure that Surge is not in my filter app list. and I follow the tutorial 
https://kb.adguard.com/en/macos/solving-problems/big-sur-issues#example-2-configuring-an-upstream-surge-proxy
it does not work. I hope there will be a feature to set up bypass DoH domains, because the DoH requests are based on HTTPS, AdGuard seems will filter it. Don't know if this is possible or not.

**Comment by fishswing** [comment]
I had the exact same problem of DNS compatibility with Surge. Seems the issue is not specifically about DoH or UDP, but about the DNS result already in the system DNS cache or not. Is it possible to fetch DNS results from Surge before sending traffic to Adguard, or just swap the sequence of sending traffic to make these two apps co-work?

**Comment by Hackl0us** [comment]
> I had the exact same problem of DNS compatibility with Surge. Seems the issue is not specifically about DoH or UDP, but about the DNS result already in the system DNS cache or not. Is it possible to fetch DNS results from Surge before sending traffic to Adguard, or just swap the sequence of sending traffic to make these two apps co-work?

Totally agreed. I tried to use the normal UDP DNS resolving and follow the AdGuard tutorial to config again. It turns out that neither of both worked...

But I found a workaround, you can boot your Mac into RecoveryOS, launch Terminal.
Type `csrutil enable --without kext` and restart your Mac.
Then change the filtering mode to Kernel Extension, it will work.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1378](https://github.com/AdguardTeam/CoreLibs/issues/1378) via [**ZenHub**](https://www.zenhub.com/)
