### ISSUE TITLE
Autodesk Fusion 360 can't connect to server after update to Big Sur

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForMac#790]
Autodesk Fusion 360 (https://www.autodesk.com/products/fusion-360/overview) can't connect to server after update to Big Sur with AdGuard for Mac activated.
Disabling of all filters, advanced tracking protection, https filtration etc don't help, the problem is solved only by turning off the main switch.

The original issue: https://github.com/AdguardTeam/AdguardFilters/issues/67653

Btw I can't reproduce this problem.

**Comment by sfionov** [comment]
Please ask every Big Sur user with problems if they use Little Snitch.

**Comment by Sergey-Lyapin** [comment]
@sfionov 
He answered:
 _I do, but I have tried to disable the Little Snitch network filter entirely, and I have the same problem with AdGuard only._

**Comment by balthisar** [comment]
Oh, I *just* sent an email via the application indicating the same problem. It didn't occur to me to check GitHub first. Anyway, yes, Fusion 360 goes offline for me whenever AdGuard is active.

I am a Little Snitch user, too, and deactivating Little Snitch does nothing to change the situation.

Because I'm on Big Sur, these are both using network extensions now instead of kernel extensions.

Fusion 360 is _not_ in my list of filtered applications in AdGuard, so I'm not even sure why it's interfering.

**Comment by sfionov** [comment]
@balthisar

Note that turning off filtering in Little Snitch doesn't help because its extension is still loaded and shown as "Running" in network preferences.

It is interfering in a way that one connection matches in both Little Snitch and AdGuard. After that Little Snitch says "I allow this connection", AdGuard says "I don't want to filter this connection because this app is not filtered", and connection should work as it does. But due to some Apple bug, CFNetwork SSL connections are failed in this case, and you can't use AdGuard's NetworkExtension with running firewall NetworkExtension.

**Comment by balthisar** [comment]
@sfionov, thanks; hopefully Apple will fix this. I did see the referenced thread, so I'm using the .pac temporarily (not preferred solution). I didn't realize this was an internal tracker when Google led me here an I posted. Sorry 'bout that!

**Comment by Chinaski1** [comment]
Hello @balthisar 

Looks like the recently released update of macOS solves this issue.

• In order to download the current beta version, you need to join the Apple Beta Software Program: https://beta.apple.com/

**Comment by balthisar** [comment]
@Chinaski1, confirmed working as an extension w/ Little Snitch in the public release of 11.2. Thanks!
