### ISSUE TITLE
regular Kernel Panics on Big Sur probably caused by AdGuard

### ISSUE THREAD

**Issue by biggie95** [AdguardTeam/AdguardForMac#822]
### Steps to reproduce

The Kernel Panics started random, there was no specific action to reproduce them. i went through all the diagnostics and possible solutions with the apple support. after analysing the Kernel Panic report which was referring to some adguard kernel extension i tried uninstalling the app from my mac. ever since that the kernel panics simply don't occur anymore. After reading this article: "https://adguard.com/de/blog/big-sur-release-comment.html" about AdGuard and Big Sur i thought it might be helpful sharing the Problems i've had. I havent tried reinstalling AdGuard so far, since i wanted to wait for the next update.

<img width="998" alt="Bildschirmfoto 2021-01-30 um 19 46 12" src="https://user-images.githubusercontent.com/62967114/106779718-8f6e1700-6647-11eb-9652-bc64c02c872a.png">

</details>

### Your environment

* macOS Big Sur 11.1
* NordVPN, Little Snitch, CleanMyMac, ParagonNTFS

**Comment by Chinaski1** [comment]
Hello there!

In the BigSur version of AdGuard, we have dispensed with the use of the kernel extension. Traffic is now filtered using the Network Extension. 
To check which mode AdGuard is running in you can in the AdGuard settings (Settings -> Network -> [Select mode](https://uploads.adguard.com/Chinaskic9rcy.png))

I also recommend that you update your macOS to version 11.2 
Compatibility issues between AdGuard and Little Snitch have been fixed in this version.
I am closing this task, but ask you to reopen it in case of a kernel panic.
It would also be advisable to send a full report to apple@adguard.com with a link to this task.
