### ISSUE TITLE
AdguardForMac crashing on 2.5.2.949 release/beta/nightly

### ISSUE THREAD

**Issue by lbeier** [AdguardTeam/AdguardForMac#838]
### Steps to reproduce
Adguard crases constantly when enabled. This has been happening since the release of 2.5.2.949. Tested all channels (release/beta/nightly) and the application crashes regardless the channel. I also tried resetting the configs to the default ones with no luck. Just need to open the application, turn Adguard on and wait couple of seconds and then the application crashes and a popup like the ones in the screenshot section shows up.

### Expected behavior
Adguard for Mac doesn't crash in release channel version.

### Actual behavior
Adguard for Mac crashes in all release/beta/nightly versions.

<details><summary>Screenshot:</summary>

<img width="468" alt="Screenshot 2021-02-21 at 22 28 14" src="https://user-images.githubusercontent.com/607692/108700447-e5c3cc80-7506-11eb-88c4-e51f57d2e80f.png">

![Screenshot 2021-02-22 at 11 58 35](https://user-images.githubusercontent.com/607692/108700460-e9efea00-7506-11eb-9a24-60113f005606.png)

![Screenshot 2021-02-22 at 11 59 30](https://user-images.githubusercontent.com/607692/108700476-f116f800-7506-11eb-8305-2dd38eeed584.png)
</details>

### Customer ID 
I didn't receive any customer id when submitting the diagnostic. I did receive a ticket id. Let me know if it is relevant.

### Your environment

* Environment name and version: Mac 16" 2019, BigSur 11.2.1 (20D74)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by Chinaski1** [comment]
Hello @lbeier 

Could you please email us at support@adguard.com with a link to this task on GitHub so we can find out your email address? This is necessary so that we can look up your crash-report.

We have also released the Nightly version today which probably solves similar issues.
Please install it and let us know the result.
Download link: agrd.io/mac_nightly

We apologize for the temporary inconvenience.

**Comment by Chinaski1** [comment]
Hello @lbeier 

Could you please email us at support@adguard.com with a link to this task on GitHub so we can find out your email address? This is necessary so that we can look up your crash-report.

We have also released the Nightly version today which probably solves similar issues.
Please install it and let us know the result.
Download link: agrd.io/mac_nightly

We apologize for the temporary inconvenience.

**Comment by xavez** [comment]
I was having the same issue. The nightly build fixes it for me.

**Comment by Chinaski1** [comment]
[Users](https://forum.adguard.com/index.php?threads/adguard-for-macos-2-5-2-949.41980/page-2#post-208608) who have also encountered this issue have confirmed that the problem has been fixed in Nightly 2.5.2.952
