### ISSUE TITLE
AdGuard fails to launch itself on the system startup

### ISSUE THREAD

**Issue by lolka4toli** [AdguardTeam/AdguardForMac#864]
### Steps to reproduce
1. Restart your Mac
2. Log into your profile
3. Face a crash

### Expected behavior
AdGuard should start as always

### Actual behavior
AdGuard fails to autostart, but after that it launches fine by a user

### Customer ID/logs
Collecting. 

### Spotted on macOS versions:
10.12.6
10.14.6
11.3

**Comment by Chinaski1** [comment]
A similar issue is also discussed on [AdGuard Form](https://forum.adguard.com/index.php?threads/startup-error.42207/#post-210206).
One of the users sent the log files.
Archive attached to the task

**Comment by awslabspl** [comment]
@lolka4toli 

> Face a crash

and

> AdGuard fails to autostart

Impossible. It cannot crash when its not started.

**Comment by LesterJitsi** [comment]
This issue does still exist on 10.14.6. It seems to be solved by disabling DNS protection. I filed two support requests yesterday.

**Comment by vsc42** [comment]
The problem is still occurring with MacOS 12.2.1 and AdGuard Application version 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72), where the problem occurs on one of three identically configuration systems. Notable is that when LittleSnitch is loaded the problem presents on boot. It appears there is a conflict with LittleSnitch. If AdGuard is set to not load on boot, but is started after the machine is stable AdGuard loads without issue. While I have tried to find why only one of the three systems has this issue, nothing in the logs points to an answer.

Additionally debugging is difficult given debug logging is always disabled on boot, even if enable prior to a reboot. Thus detailed logging, as required by AdGuard, has not been provided.

**Comment by Chinaski1** [comment]
Hello @vsc42 

OS version: 12.3 Beta / 11.6 BigSur
AdGuard for macOS: 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)
Little snitch version: Version 5.3.2 (6229)

The issue is not reproduced.
Please specify in what mode Little Snitch works.
Maybe there are some other features to consider?

In any case, you can send logs we tried to figure out the causes of the issue. (apple@adguard.com)
