### ISSUE TITLE
WiFi authorization popup doesn't show up while AdGuard is on

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardForMac#892]
### Steps to reproduce

1. Enable AdGuard
2. Try to connect to any open WiFi network

### Expected behavior
Authorization popup should be shown

### Actual behavior
The popup doesn't show up

**Comment by Eugene-Savenko** [comment]
User replied: Открытый вайфай в пиццерии.

There's also been a good bunch of complaints on AdGuard for Mac blocking captive portal opening on Macs. These are probably not related, by anyway.

**Comment by chizhang9135** [comment]
I have facing this issue. It will show me a blank page when trying to log in to free wifi. The captive page always loaded error.

**Comment by Eugene-Savenko** [comment]
I guess this new report belongs here as well (helpdesk ID 588069):

I'm using AdGuard for Mac 2.7.0.1094 with all default filter lists updated and AdGuard DNS activated.

Expected behavior: When traveling on a train of [Deutsche Bahn](https://streaklinks.com/A-tyzZtBQYb2fcoPGQvy49QH/https%3A%2F%2Fwww.bahn.de%2Fservice%2Fzug%2Fice-portal), I would log into their Wifi to access the internet and also the internal website of the train with movies and latest info on the trip: https://www.iceportal.de/

Current behavior: With AdGuard activated, I cannot even access the WifI (Most likely because it blocks the pop up required to check the T&C of the Wifi). Once AdGuard is deactivated I can access the WiFi through the pop up, but whenever I want to access the ICEportal.de I'm being redirected to [this website](https://streaklinks.com/A-tyzZxNDb7B5Tr0hg3-KzwF/https%3A%2F%2Fwww.bahn.de%2Fservice%2Fzug%2Fice-portal), probably because the browser or the Wifi cannot detect that I'm actually logged into the wifi on the train.

What is disappointing is that even with AdGuard completely turned off I cannot access the page.

**Comment by ogirginc** [comment]
I have the same problem. For example, when I go to a Starbucks to work;

1. Disable AdGuard for Mac.
2. Connect to the Wi-Fi.
	a. If you still can't see the pop-up, turn-off the AdGuard for Mac completely.
	b. Try to connect again.
3. Accept legal stuff on the pop-up.
4. Enable AdGuard for Mac.

**Comment by Aydinv13** [comment]
@chizhang9135 @ogirginc 
Could you check if the problem persists with the latest version?

**Comment by ogirginc** [comment]
Hey @Aydinv13, I just had a chance to go to the same Starbucks and confirm that I did not have the same issue any more. I was able to see the pop even though the AdGuard was running on the background.

```
Application version 2.8.1.1147 release (CL-1.9.86, DNS-1.7.22)
```
