### ISSUE TITLE
Logs are either buggy or unclear

### ISSUE THREAD

**Issue by ploum** [AdguardTeam/AdguardForMac#98]
There are a bunch of problems with logs:

1. I don't see any difference between the log levels.
2. Basically, the log viewer are always empty.
3. When I disable Adguard, then some stuff appear in the log viewer.
4. The "blocked" checkbox always show an empty list.

It's a bit like the logging is done after the blocking by Adguard, thus not showing anything when adguard is enabled.

Using 1.2.0 on latest OSX.

**Comment by vbagirov** [comment]
1) Logging level doesn't affect what is shown in log viewer. It is purely for debug logs which are attached to a message when you contact a support. 

2) Strange, but there is a bug that causes Adguard to crash when Filterthat log is opened, it is fixed in beta version. Maybe this one is fixed there too.

3) That's normal. Filtering log shows all requests no matter how they are affected by Adguard, if affected at all.

4) This might very well be a correct behavior. If there are no blocked requests currently (they are shown with a reddish background), nothing will be shown when you click on 'Show only blocked requests'.
