### ISSUE TITLE
Can't add FirefoxPWA's patched Firefox.app into filtered applications

### ISSUE THREAD

**Issue by wzxu** [AdguardTeam/AdguardForMac#993]
[FirefoxPWA](https://github.com/filips123/FirefoxPWA) is a way to install PWA as an app with Firefox. On macOS, it downloads a separate instance of Firefox to ~/Library/Application Support/firefoxpwa/runtime/Firefox.app, and patches the binary to do some additional magic for PWA to work. However, I'm not able to add this Firefox.app into filtered applications, so I'm seeing many ads.

### Steps to reproduce
1. Install FirefoxPWA's extension as well as the native counterpart (via Homebrew on macOS)
2. Create a PWA with it
3. Try to add the patched Firefox.app into filtered applications

### Expected behavior
The separate, patched Firefox.app should be added to the list, and filtering should work

### Actual behavior
The app is not added to the list and filtering is not working. AdGuard instead highlights the original Firefox.app in the list, which locates in /Applications/Firefox.app, as if they're the same one, but they're not.

Then I tried adding the PWA app it creates in ~/Applications (for example ~/Applications/Spotify.app) into filtered applications. It showed up in the list, but the ads are still not filtered this way, so I think being able to add that patched Firefox.app is the key.

Finally I granted AdGuard full disk access then retried, but it doesn't work. And I tried trashing the original Firefox.app & delete its entry from the list before adding the patched one. It did show up in the list this way, but filtering is still not working.

### Customer ID 
Not seeing a "Customer ID" in the email reply? Ticket number is 554896. Or is it this strange string at the end? -> [X7LYQM-557Q] 

### Your environment
* Environment name and version: Firefox 94.0.1, macOS 12.0.1
* Any specific potentially conflicting software installed: LuLu firewall

**Comment by dakuzmin69** [comment]
Hello there!

The impossibility of filtering PWA apps is due to the way the FirefoxPWA solution is implemented. We have opened an [issue](https://github.com/filips123/PWAsForFirefox/issues/131).

The original Firefox.app and the patched Firefox.app are the same from the point of view of the system, since they have the same bundle identifier. You can see it visually as follows:

1. Set the original Firefox.app as the default browser
2. Delete original Firefox.app
3. Perform an action that should open the default browser.
 
The patched Firefox.app will open.

**Comment by wzxu** [comment]
Thanks a lot for the explanation and opening the issue there! Will be keeping an eye on it 👀
