### ISSUE TITLE
Unable to whitelist rule from AdGuard Tracking Protection filter

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [AdguardTeam/AdguardForMac#996]
### Steps to reproduce
1. Enable _AdGuard Tracking Protection filter_
2. Add user rule `@@||bb.com.br^$important,document`
3. Navigate to https://investimentos.bb.com.br/recursos/directives/piwik/piwik.directive.js?v=2.9.10

### Expected behavior
URL should not be blocked by AdGuard while _AdGuard Tracking Protection filter_ is enabled and the user rule is configured.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/7753096/143277762-eb01ea2c-db64-4fd6-ad9c-1683573f97f4.png)

</details>

### Actual behavior
URL is blocked by AdGuard while _AdGuard Tracking Protection filter_ is enabled and the user rule is configured.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/7753096/143277782-7ab52126-d43e-4e99-a762-e3edffe82819.png)

![image](https://user-images.githubusercontent.com/7753096/143277805-bc078aae-4a2b-46a9-b7d2-105132a7eefb.png)

</details>

### Customer ID 
555816

### Your environment
* macOS Monterey 12.0.1 (21A559)
* Safari 15.1 (17612.2.9.1.20)
* AdGuard 2.6.1.1051 release (CL-1.8.221, DNS-1.6.58)

**Comment by Chinaski1** [comment]
Hello there!

The thing is that the rule `/piwik.$image,script,domain=~matomo.org|~piwik.org|~piwik.pro` does not block the common domain, it is a separate script. That's why you need to unblock it separately.

Use this rule to unblock script directly: `@@||investimentos.bb.com.br/recursos/directives/piwik/piwik.directive.js?v=2.9.10`
